server:
   port: 9090
spring:
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     username: root
     password: root
     url: jdbc:mysql://127.0.0.1:3306/taotao?characterEncoding=utf8
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.taotaox.manager.entity
dubbo:
   scan:
       basePackages: com.taotaox.sso.service.provider
   application:
       id: sso-service-provider
       name: sso-service-provider
   protocol:
       id: dubbo
       name: dubbo
       port: 12345
   registry:
       id: my-registry
       address: N/A
redis:
   host: localhost
   port: 6379
   timeout: 2000
   password:
   db:
     index: 1