server:
  port: 8082
  context-path: /taotaox
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/taotao
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.taotaox.manager.entity