server:
  port: 8081
spring:
   datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://127.0.0.1:3306/taotao?characterEncoding=utf8
       username: root
       password: root

INDEX_CONTENT_REDIS_KEY=INDEX_CONTENT_REDIS_KEY
# 商品信息
REDIS_ITEM_KEY=REDIS_ITEM_KEY
# 过期时间，默认为1天
REDIS_ITEM_EXPIRE=86400

# 列表
INDEX_CATEGORY_REDIS_KEY=INDEX_CATEGORY_REDIS_KEY