server:
   port: 8088
   token:
      key: loginid
   session:
      cookie:
       domain: localhost
       httpOnly: true
       name: taotaox-sso
       path: /
spring:
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     username: root
     password: root
     url: jdbc:mysql://127.0.0.1:3306/taotao?characterEncoding=utf8
dubbo:
   application:
       id: sso-service-consumer
       name: sso-service-consumer
   protocol:
       id: dubbo
       name: dubbo
       port: 12345