REST_BASE_URL: http://127.0.0.1:8081/rest/rest
REST_INDEX_AD_URL: /public/content/list/89

# 搜索服务URL
SEARCH_BASE_URL: http://127.0.0.1:8081/search/search/query
# 商品基本信息url
ITEM_INFO_URL: /item/info/
# 商品描述
ITEM_DESC_URL: /item/desc/
# 商品规格参数url
ITEM_PARAM_URL: /item/param/

# 单点登录系统的url
SSO_BASE_URL: http://127.0.0.1:8083

# 拦截器
SSO_INTERCEPTOR: http://sso.tianfang1214.cn

TAOTAOX_MAIN: http://taotaox.tianfang1314.cn

# 根据token获取用户信息url
SSO_USER_TOKEN: /user/token

SSO_PAGE_LOGIN: /page/login

# 订单系统基础url
ORDER_BASE_URL: http://127.0.0.1:8081/order/order

ORDER_CREATE_URL: /create